<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ContractSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('contract')->insert([
            // Active Contracts
            [
                'description' => 'Construction of a two-story residential building',
                'status' => 'ongoing',
                'contract_name' => 'Residential Building Project',
                'location' => 'Davao City',
                'designation' => 'Project Engineer',
                'duration_in_days' => 200,
                'amount' => 2500000.00,
                'date' => Carbon::now()->subDays(50)->toDateString(),
                'submitted_by_employee_id' => 1,
                'signing_authority_employee_id' => 2,
                'authorized_representative_employee_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Renovation of an office building',
                'status' => 'ongoing',
                'contract_name' => 'Office Renovation Project',
                'location' => 'Tagum City',
                'designation' => 'Construction Supervisor',
                'duration_in_days' => 120,
                'amount' => 1200000.00,
                'date' => Carbon::now()->subDays(30)->toDateString(),
                'submitted_by_employee_id' => 4,
                'signing_authority_employee_id' => 5,
                'authorized_representative_employee_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Road widening and drainage improvement',
                'status' => 'ongoing',
                'contract_name' => 'Infrastructure Improvement Project',
                'location' => 'Panabo City',
                'designation' => 'Civil Engineer',
                'duration_in_days' => 300,
                'amount' => 4500000.00,
                'date' => Carbon::now()->subDays(100)->toDateString(),
                'submitted_by_employee_id' => 7,
                'signing_authority_employee_id' => 8,
                'authorized_representative_employee_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Construction of a commercial complex',
                'status' => 'ongoing',
                'contract_name' => 'Commercial Complex Project',
                'location' => 'Mati City',
                'designation' => 'Site Manager',
                'duration_in_days' => 400,
                'amount' => 8000000.00,
                'date' => Carbon::now()->subDays(90)->toDateString(),
                'submitted_by_employee_id' => 10,
                'signing_authority_employee_id' => 11,
                'authorized_representative_employee_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'description' => 'Bridge rehabilitation project',
                'status' => 'ongoing',
                'contract_name' => 'Bridge Rehabilitation Project',
                'location' => 'Compostela Valley',
                'designation' => 'Structural Engineer',
                'duration_in_days' => 180,
                'amount' => 3500000.00,
                'date' => Carbon::now()->subDays(20)->toDateString(),
                'submitted_by_employee_id' => 13,
                'signing_authority_employee_id' => 14,
                'authorized_representative_employee_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Past Contracts
            [
                'description' => 'Completed residential subdivision development',
                'status' => 'completed',
                'contract_name' => 'Subdivision Development Project',
                'location' => 'Digos City',
                'designation' => 'Construction Foreman',
                'duration_in_days' => 365,
                'amount' => 12000000.00,
                'date' => Carbon::now()->subYears(1)->toDateString(),
                'submitted_by_employee_id' => 1,
                'signing_authority_employee_id' => 2,
                'authorized_representative_employee_id' => 3,
                'created_at' => Carbon::now()->subYears(1)->toDateTimeString(),
                'updated_at' => Carbon::now()->subYears(1)->toDateTimeString(),
            ],
            [
                'description' => 'Road repair and resurfacing project',
                'status' => 'completed',
                'contract_name' => 'Road Repair Project',
                'location' => 'Samal Island',
                'designation' => 'Project Coordinator',
                'duration_in_days' => 90,
                'amount' => 2000000.00,
                'date' => Carbon::now()->subMonths(6)->toDateString(),
                'submitted_by_employee_id' => 4,
                'signing_authority_employee_id' => 5,
                'authorized_representative_employee_id' => 6,
                'created_at' => Carbon::now()->subMonths(6)->toDateTimeString(),
                'updated_at' => Carbon::now()->subMonths(6)->toDateTimeString(),
            ],
            [
                'description' => 'Construction of a school building',
                'status' => 'completed',
                'contract_name' => 'School Building Project',
                'location' => 'Marilog District',
                'designation' => 'Project Manager',
                'duration_in_days' => 150,
                'amount' => 5000000.00,
                'date' => Carbon::now()->subMonths(9)->toDateString(),
                'submitted_by_employee_id' => 7,
                'signing_authority_employee_id' => 8,
                'authorized_representative_employee_id' => 9,
                'created_at' => Carbon::now()->subMonths(9)->toDateTimeString(),
                'updated_at' => Carbon::now()->subMonths(9)->toDateTimeString(),
            ],
            [
                'description' => 'Warehouse construction for logistics',
                'status' => 'canceled',
                'contract_name' => 'Warehouse Construction',
                'location' => 'Davao del Sur',
                'designation' => 'Site Engineer',
                'duration_in_days' => 180,
                'amount' => 8000000.00,
                'date' => Carbon::now()->subMonths(12)->toDateString(),
                'submitted_by_employee_id' => 10,
                'signing_authority_employee_id' => 11,
                'authorized_representative_employee_id' => 12,
                'created_at' => Carbon::now()->subMonths(12)->toDateTimeString(),
                'updated_at' => Carbon::now()->subMonths(12)->toDateTimeString(),
            ],
            [
                'description' => 'Completed mall construction',
                'status' => 'completed',
                'contract_name' => 'Mall Construction Project',
                'location' => 'Davao City',
                'designation' => 'Construction Lead',
                'duration_in_days' => 400,
                'amount' => 25000000.00,
                'date' => Carbon::now()->subYears(2)->toDateString(),
                'submitted_by_employee_id' => 13,
                'signing_authority_employee_id' => 14,
                'authorized_representative_employee_id' => 15,
                'created_at' => Carbon::now()->subYears(2)->toDateTimeString(),
                'updated_at' => Carbon::now()->subYears(2)->toDateTimeString(),
            ],
        ]);
    }
}
