<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Define the fixed projects for each contract
        $projectsData = [
            // Residential Building Project (Contract 1)
            [
                'project_name' => 'Residential Building Project - Phase 1',
                'status' => 'ongoing',
                'street_address' => '123 Main St',
                'barangay' => 'Barangay 1',
                'city' => 'Davao City',
                'province' => 'Davao Region',
                'zip_code' => '8000',
                'country' => 'Philippines',
                'duration_in_days' => 100,
                'num_of_units' => 5,
                'abc_value' => 500000.00,
                'submitted_by_employee_id' => 1,
                'signing_authority_employee_id' => 2,
                'contract_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Residential Building Project - Phase 2',
                'status' => 'ongoing',
                'street_address' => '124 Main St',
                'barangay' => 'Barangay 2',
                'city' => 'Davao City',
                'province' => 'Davao Region',
                'zip_code' => '8000',
                'country' => 'Philippines',
                'duration_in_days' => 100,
                'num_of_units' => 5,
                'abc_value' => 500000.00,
                'submitted_by_employee_id' => 1,
                'signing_authority_employee_id' => 2,
                'contract_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Office Renovation Project (Contract 2)
            [
                'project_name' => 'Office Renovation Project - Phase 1',
                'status' => 'ongoing',
                'street_address' => '456 Office Ave',
                'barangay' => 'Barangay 3',
                'city' => 'Tagum City',
                'province' => 'Davao Region',
                'zip_code' => '8100',
                'country' => 'Philippines',
                'duration_in_days' => 60,
                'num_of_units' => 3,
                'abc_value' => 400000.00,
                'submitted_by_employee_id' => 4,
                'signing_authority_employee_id' => 5,
                'contract_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Office Renovation Project - Phase 2',
                'status' => 'ongoing',
                'street_address' => '457 Office Ave',
                'barangay' => 'Barangay 4',
                'city' => 'Tagum City',
                'province' => 'Davao Region',
                'zip_code' => '8100',
                'country' => 'Philippines',
                'duration_in_days' => 60,
                'num_of_units' => 3,
                'abc_value' => 400000.00,
                'submitted_by_employee_id' => 4,
                'signing_authority_employee_id' => 5,
                'contract_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Infrastructure Improvement Project (Contract 3)
            [
                'project_name' => 'Infrastructure Improvement Project - Phase 1',
                'status' => 'ongoing',
                'street_address' => '789 Roadway',
                'barangay' => 'Barangay 5',
                'city' => 'Panabo City',
                'province' => 'Davao Region',
                'zip_code' => '8111',
                'country' => 'Philippines',
                'duration_in_days' => 150,
                'num_of_units' => 8,
                'abc_value' => 1500000.00,
                'submitted_by_employee_id' => 7,
                'signing_authority_employee_id' => 8,
                'contract_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Infrastructure Improvement Project - Phase 2',
                'status' => 'ongoing',
                'street_address' => '790 Roadway',
                'barangay' => 'Barangay 6',
                'city' => 'Panabo City',
                'province' => 'Davao Region',
                'zip_code' => '8111',
                'country' => 'Philippines',
                'duration_in_days' => 150,
                'num_of_units' => 8,
                'abc_value' => 1500000.00,
                'submitted_by_employee_id' => 7,
                'signing_authority_employee_id' => 8,
                'contract_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Commercial Complex Project (Contract 4)
            [
                'project_name' => 'Commercial Complex Project - Phase 1',
                'status' => 'ongoing',
                'street_address' => '123 Commerce St',
                'barangay' => 'Barangay 7',
                'city' => 'Mati City',
                'province' => 'Davao Region',
                'zip_code' => '8200',
                'country' => 'Philippines',
                'duration_in_days' => 200,
                'num_of_units' => 10,
                'abc_value' => 2500000.00,
                'submitted_by_employee_id' => 10,
                'signing_authority_employee_id' => 11,
                'contract_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Commercial Complex Project - Phase 2',
                'status' => 'ongoing',
                'street_address' => '124 Commerce St',
                'barangay' => 'Barangay 8',
                'city' => 'Mati City',
                'province' => 'Davao Region',
                'zip_code' => '8200',
                'country' => 'Philippines',
                'duration_in_days' => 200,
                'num_of_units' => 10,
                'abc_value' => 2500000.00,
                'submitted_by_employee_id' => 10,
                'signing_authority_employee_id' => 11,
                'contract_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Bridge Rehabilitation Project (Contract 5)
            [
                'project_name' => 'Bridge Rehabilitation Project - Phase 1',
                'status' => 'ongoing',
                'street_address' => '345 Bridge Rd',
                'barangay' => 'Barangay 9',
                'city' => 'Compostela Valley',
                'province' => 'Davao Region',
                'zip_code' => '8300',
                'country' => 'Philippines',
                'duration_in_days' => 90,
                'num_of_units' => 4,
                'abc_value' => 1000000.00,
                'submitted_by_employee_id' => 13,
                'signing_authority_employee_id' => 14,
                'contract_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Bridge Rehabilitation Project - Phase 2',
                'status' => 'ongoing',
                'street_address' => '346 Bridge Rd',
                'barangay' => 'Barangay 10',
                'city' => 'Compostela Valley',
                'province' => 'Davao Region',
                'zip_code' => '8300',
                'country' => 'Philippines',
                'duration_in_days' => 90,
                'num_of_units' => 4,
                'abc_value' => 1000000.00,
                'submitted_by_employee_id' => 13,
                'signing_authority_employee_id' => 14,
                'contract_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert all project data into the database
        DB::table('project')->insert($projectsData);
    }
}
